/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View.component;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.Icon;
import javax.swing.ImageIcon;

import com.mysql.cj.util.StringUtils;

import model.ASanPham;

/**
 *
 * @author trong
 */
public class Product extends javax.swing.JPanel {
    private boolean selected;
    private ASanPham data;

    /** Creates new form Product */
    public Product() {
        initComponents();
        setOpaque(false);
        setCursor(new Cursor(Cursor.HAND_CURSOR) {
        });
    }
    
     public ASanPham getData() {
		return data;
	}

	public boolean isSelected() {
        return selected;
    }

    public void setSelected(boolean selected) {
        this.selected = selected;
        repaint();
    }

    public void setData(ASanPham data) {

        this.data = data;
//                DecimalFormat df = new DecimalFormat("$#,##0.00");
        lbCount.setText(data.getSoLuong()+"");
       
        String nameProduct = data.getTenSanPham();
//        int maxLength = 20;
//        if (nameProduct.length()>maxLength) {
//            lbName.setText(nameProduct.substring(0, maxLength)+"...");
//		}else {
			lbName.setText("<html>"+nameProduct+"</html>");
//		}
//        System.out.println(data.getListUrl().get(0));
        try {
            Icon ic =  new ImageIcon(getClass().getResource(data.getListUrl().get(0)));
			pictureBox1.setImage(ic);
		} catch (NullPointerException e) {
			// TODO: handle exception
		
		}
        lbPrice.setText(data.formatCurrencyVN(data.getDonGia()));
        
    }

    @Override
    public void paint(Graphics grphcs) {
         Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(new Color(242, 242, 242));
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 20, 20);
        if (selected) {
            g2.setColor(new Color(94, 156, 255));
            g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 20, 20);
        }
        g2.dispose();
        super.paint(grphcs);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lbName = new javax.swing.JLabel();
        pictureBox1 = new View.swing.PictureBox();
        lbPrice = new javax.swing.JLabel();
        lbName2 = new javax.swing.JLabel();
        lbCount = new javax.swing.JLabel();

        lbName.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbName.setForeground(new java.awt.Color(76, 76, 76));
        lbName.setText("Product name");

        pictureBox1.setImage(new javax.swing.ImageIcon(getClass().getResource("/View/img_product/gach.jpg"))); // NOI18N

        lbPrice.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbPrice.setForeground(new java.awt.Color(76, 76, 76));
        lbPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPrice.setText("500,000đ");

        lbName2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lbName2.setForeground(new java.awt.Color(76, 76, 76));
        lbName2.setText("Giá:");

        lbCount.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lbCount.setForeground(new java.awt.Color(76, 76, 76));
        lbCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCount.setText("5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lbName2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4))
                    .addComponent(pictureBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pictureBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lbCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbName2)
                    .addComponent(lbPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JLabel lbCount;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbName2;
    private javax.swing.JLabel lbPrice;
    private View.swing.PictureBox pictureBox1;
    // End of variables declaration                   

}
